### ISSUE TITLE
想问问备注样式与剪贴板数据能不在一行显示吗？

### ISSUE THREAD

**Issue by Achuan-2** [GFDGIT/CopyQ_lazy#1]
图片文件的预览是把路径当成备注的，可是预览时一行显示图片就在很右边
![image](https://github.com/GFDGIT/CopyQ_lazy/assets/60436214/2d91541e-cad3-4b5e-84f9-97be687f6d2f)

**Comment by Achuan-2** [comment]
![image](https://github.com/GFDGIT/CopyQ_lazy/assets/60436214/cdf0ba9e-a75a-4f82-ac9b-fff7c7d12113)
重装了下Copq就好了，不知道为什么

**Comment by GFDGIT** [comment]
设置-条目-备注，可以修改备注的位置

**Comment by Achuan-2** [comment]
哦哦，感谢
