### ISSUE TITLE
请问简洁模式如何实现

### ISSUE THREAD

**Issue by GongLe** [GFDGIT/CopyQ_lazy#2]
![Clip_2024-08-20_14-29-26](https://github.com/user-attachments/assets/4ce1fc9e-1f69-4baa-8bc9-b3685215eb10)

### 请问简洁模式如何实现，导入配置开启简洁模式工具栏无法隐藏
![Clip_2024-08-20_14-30-25](https://github.com/user-attachments/assets/d39e9d13-3f59-473f-a031-0f0e8f58909c)

**Comment by GongLe** [comment]
额 看到了， 是在9.0版本简洁主题报错

**Comment by GongLe** [comment]
9.0版本简洁主题报错

**Comment by GFDGIT** [comment]
> 9.0版本简洁主题报错

我这边试了没有报错，但是很卡顿，切换很慢，可能是哪里兼容有问题了，等有空看看能不能解决。

**Comment by GFDGIT** [comment]
似乎9.1版本修复这个问题了，你试试看
